### ISSUE TITLE
why so long?

### ISSUE THREAD

**Issue by ILMaltster** [egramtel/tdsharp#109] opened 2022-04-03 17:53 UTC
I get chats in 62 seconds, why is it taking so long?
![image](https://user-images.githubusercontent.com/100075945/161441181-43282114-7518-4cb0-a47c-6ffbd959d801.png)

**Comment by ForNeVeR** [comment] 2022-04-23 09:32
Could you please test without `.Result`? That one is suspicious.

**Comment by ILMaltster** [comment] 2022-04-23 16:41
Again... receives a response from 50 to 70 seconds
![Безымянный](https://user-images.githubusercontent.com/100075945/164915206-664268ab-09f4-4b50-81bf-3ce52ae1008d.png)

**Comment by ForNeVeR** [comment] 2022-04-24 05:34
Unfortunately, I cannot reproduce this behavior: in my case, this exact code works instantly.

What kind of application do you use? Is this a UI app? Could it be some problem with your synchronization context?

Try assing `.ConfigureAwait(false)` after `.ExecuteAsync(…)`.

**Comment by ILMaltster** [comment] 2022-04-27 20:00
Everything works in the console application. When I develop a WPF(.NET 5.0) application, some problems occur. Method ".ConfigureAwait(false)" didn't help :(

**Comment by nikolaykusch** [comment] 2022-08-04 04:01
Same problem. Each asynchronous request is executed in a separate thread, takes at least 40 seconds of time.

**Comment by ForNeVeR** [comment] 2022-08-04 18:51
I still suggest profiling the application.

**Comment by nikolaykusch** [comment] 2022-08-05 07:31
> I still suggest profiling the application.
Here. Base authorise. Created Client, sended TdApi.SetTdlibParameters, and TdApi.CheckDatabaseEncryptionKey. 
After sending TdApi.CheckDatabaseEncryptionKey, nothing arrive
[zip.zip](https://github.com/egramtel/tdsharp/files/9266407/zip.zip)
d

**Comment by ForNeVeR** [comment] 2022-08-06 09:09
## Regarding the slow message processing
I still have no clue. Does it reproduce without MAUI, in a simple console app you'd be able to share?

## Regarding the CPU usage
Okay, this gets interesting.

What TdSharp does is calling native function `ClientReceive` with a small timeout in an endless loop: https://github.com/egramtel/tdsharp/blob/df48525c9b67050d96f48e1273127bc8b858c7a3/TdLib/Bindings/Receiver.cs#L46-L68

A small timeout (that's 0.1 sec) is required for the client to be able to terminate in a timely manner on a cancellation token termination.

I never thought 10 native calls per second would take so much CPU time (about 16% in the profile you provided). Do events happen often in your program? I.e. do you have much traffic?

Can you please try building tdsharp yourself and increase the timeout from 0.1 to 10 in this line of code? https://github.com/egramtel/tdsharp/blob/df48525c9b67050d96f48e1273127bc8b858c7a3/TdLib/Bindings/Receiver.cs#L48

Will the CPU consumption get smaller? Will the response time get better?

**Comment by nikolaykusch** [comment] 2022-08-06 09:27
Yes, I already tried changing the timeout. Increasing it to 10 seconds reduces the load by about 5%.
I have been debugging the project for two days now, this is what I was able to discover.
All requests that do not require authorization work. Problems getting AuthorizationStateReady and beyond.
Several times there was a situation when after several requests, which were executed from 40 seconds to 2 minutes, everything returned to normal, requests were made quickly, there was no load on the processor. What was the reason - I could not figure it out.
Asynchronous requests are added to the 
```
list private readonly ConcurrentDictionary<int, Action<TdApi.Object>> _tasks; 
```
and are deleted when data arrives. 
Updates come without problems.
In general, the code itself works as it should. It seems as if the problem is in tdjson.dll
I will check the console project a little later, I will write how I get the result

**Comment by nikolaykusch** [comment] 2022-08-06 13:29
Checked the console application. Works fine, no problems.
This is really getting interesting :)

**Comment by ForNeVeR** [comment] 2022-08-06 14:12
My guess would be that tdsharp is relying on global synchronization context somehow (this is obvious global difference between console and MAUI app). I think I've cleaned it all up in #92 and released as 1.7.0.1. Could you please check that you're using that version?

**Comment by nikolaykusch** [comment] 2022-08-06 14:25
I was using version 1.8.1.1 from nuget
Then linked the code from github to figure out what was wrong.
Now checked Nuget 1.7. No changes, CPU load and long wait times

**Comment by nikolaykusch** [comment] 2022-08-10 09:09
Eventually I was able to get it to work.
Tried to figure out what could be wrong in Tdyson, called
```
TdLibBindingsExtensions.SetLogFilePath 
TdLibBindingsExtensions.SetLogVerbosityLevel
```
in the client constructor and everything worked. There are no delays, there is no load on the processor. I have no idea why :)
Set Td Log Level to Error so that logs take up less memory

**Comment by ForNeVeR** [comment] 2022-08-13 19:38
Wow, that's unusual. Perhaps you had a lot of traffic, and logging took a significant amount of time? Even though the logs are usually going nowhere in a UI application.

Before this change, were you setting another log level?

**Comment by nikolaykusch** [comment] 2022-08-14 14:37
I don't think there was much traffic. Basically just basic updates.
Yes, I set "Info" first. The logs were fine. Not much time passed between the request and the answer. Turned off logs - delays again.

**Comment by ForNeVeR** [comment] 2022-08-16 20:04
You use that in a GUI app with no console, right?

**Comment by antonGritsenko** [comment] 2022-08-17 11:48
Same story for me. With 1.7 it was quite fast, with 1.8 it more than 30 seconds to load just 10 chats. 
Also same for the Connection events, using 1.7 I have about 3-5 seconds between Connecting and ConnectionReady, with 1.8 it more then 30 seconds (always). Here is the logs from 1.8, it almost a minute:
```
2022-08-17 08:38:47.1965|DEBUG|TelegramClient.TClient|connection state: $TdLib.TdApi+ConnectionState+ConnectionStateConnecting (connectionStateConnecting, )
2022-08-17 08:39:28.7697|DEBUG|TelegramClient.TClient|connection state: $TdLib.TdApi+ConnectionState+ConnectionStateUpdating (connectionStateUpdating, )
2022-08-17 08:39:36.5610|DEBUG|TelegramClient.TClient|connection state: $TdLib.TdApi+ConnectionState+ConnectionStateReady (connectionStateReady, )
```

PS Migration from 1.7 to 1.8.1 fully failed, reverted back.

**Comment by antonGritsenko** [comment] 2022-08-17 12:07
Using
```
TdLibBindingsExtensions.SetLogFilePath 
TdLibBindingsExtensions.SetLogVerbosityLevel
```
solved for me both issues

**Comment by ForNeVeR** [comment] 2022-08-17 17:32
I wasn't still able to reproduce the issue. I guess at this stage someone has to upload a public source code for us to reproduce this, so we'll be able to either diagnose or fix it.

**Comment by antonGritsenko** [comment] 2022-08-17 17:53
@ForNeVeR you now have access to the private repo. Please upgrade the packages to 1.8 and uncomment the code at MainWindow.xaml.cs line 178. Sorry for the code quality, this is just a quick PoC.

**Comment by ForNeVeR** [comment] 2022-08-17 17:56
Ok, I'll try to take a look at the weekend.

**Comment by antonGritsenko** [comment] 2022-08-17 17:57
@ForNeVeR also pushed the **tdlin_1_8** branch, you can take it. Just remove line line 46-47 at \TClient\TClient.cs to repro the issue. Thank you.

**Comment by antonGritsenko** [comment] 2022-08-17 18:32
Small update: with SetLogFilePath and SetLogVerbosityLevel the TDLib working INCREDIBLE fast! Every single event, every call to TDLib function now happened almost instant. I'm impress from one hand and I bit warried from another. Before changes the entire warm up of the app took about 2-3 minutes (connection, loadChats, waiting until chats loaded in UpdateNewChat). 

Now it took 9 (!!!!) seconds
```
2022-08-17 21:30:31.3935|DEBUG|TelegramClient.TClient|Waiting connection init...
........
2022-08-17 21:30:40.3587|DEBUG|TelegramClient.TClient|Unhanled update: TdLib.TdApi+Update+UpdateChatPosition
```

**Comment by antonGritsenko** [comment] 2022-08-17 18:39
and another update (sorry for spamming): SetLogVerbosityLevel  is enough to make it work fast.

**Comment by nikolaykusch** [comment] 2022-08-17 20:55
I see such magic for the first time :)
Perhaps it is worth adhering to the principle "It works - do not touch it", add logging by default to the client's constructor and leave it that way?

**Comment by nikolaykusch** [comment] 2022-08-17 21:04
> You use that in a GUI app with no console, right?


Yes, MAUI.
Now I've repackaged this library to the MAUI class library, use .Net 6.0.

**Comment by ForNeVeR** [comment] 2022-08-19 17:11
@antonGritsenko, your program (or at least the version which is slow) seems to use `GetAwaiter().GetResult()` a lot. And also, there's a lot of `async void`, which I cannot approve.

Most likely, the reason is this `GetAwaiter().GetResult()`. This action may take any amount of time (depending on the target synchronization context) or even cause a deadlock. _Especially_ if you call it in `TdClient::UpdateReceived` handler (which calls its subscribers synchronously inside of the client event loop).

@nikolaykusch, is there a chance you have any `Task.Result` or `GetAwaiter().GetResult()` calls in your program as well?

**Comment by antonGritsenko** [comment] 2022-08-19 17:26
@ForNeVeR the async void is the normal practice for the event handlers in WPF. Actually, there is no choice there.

**Comment by ForNeVeR** [comment] 2022-08-19 17:28
No it is not, and I forbid you to use `async void` in any context. Just don't. It is bad.

**Comment by antonGritsenko** [comment] 2022-08-19 17:36
@ForNeVeR not following you. All giudes just days that. Moreover, the event handler will not allow you to use Task as return type, only the void.
And this do not explain why everything works when logging enabled.

**Comment by ForNeVeR** [comment] 2022-08-19 17:38
**Why is `async void` wrong?** Because of the error handling.

1. Some runtime versions or poorly configured .NET runtimes will just outright crash if an exception is thrown from `async void`.
2. In other cases, the exception will be just ignored at best (so no logging, no useful handling, nothing).
3. Sometimes, it may break a poorly written task scheduler, or outright crash the whole program (if the scheduler is caraless and prefers unguarded execution on thread pool).
4. And sometimes you may catch and log the exception via `Task.UnobservedException` or via your synchronization context facilities.

That's a lot of "sometimes" and "maybe crash" for me. And the answer is extremely easy: just don't use that. `async void` is a poorly designed feature for people to get into asynchrony, and it never was designed to be used in production.

**What to do instead?** Simple: use `NoAwait()`.

Let's consider a typical case of asynchronous event handler.

```csharp
async void OnEvent() // this code is WRONE
{
  await DoThis();
  await DoThat();
}
```

Rewrite as this:
```
void OnEvent()
{
  async Task Go()
  {
    await DoThis();
    await DoThat();
  }
  Go().NoAwait();
}
```

**What is `NoAwait`?** Even simpler. Catch exception and write to log. [See an example here](https://github.com/JetBrains/rd/blob/b8dce02e660ee3bce10f02a3a6cbd3981758379a/rd-net/Lifetimes/Threading/TaskEx.cs#L18-L26).

**Comment by ForNeVeR** [comment] 2022-08-19 17:40
> And this do not explain why everything works when logging enabled.

It doesn't have to. The real problem is `Task::Result` and `GetAwaiter().GetResult()` invocations. I don't believe it has anything to do with the logging. Perhaps the timing change without (or with?) logging makes the program more or less resilient to this kind of deadlocks.

**Comment by antonGritsenko** [comment] 2022-08-19 18:17
I think we talking about different things, you are about c# event handling, but ipm talking about wpf UI event handling, which is a bit different story, especially in threading (and in 10+ years of using wpf this is the first library that cause the issue with async void in UI handlers) . But in any case, I will try your workaround and will report.

**Comment by nikolaykusch** [comment] 2022-08-22 16:12
> @nikolaykusch, is there a chance you have any `Task.Result` or `GetAwaiter().GetResult()` calls in your program as well?
No. Everywhere async Task / await SomeMetgod

Anton Hrytsenko is right, it does not seem that this is the problem. The more we write on different platforms.
I think the problem lies in the library from Telegram.
Sometime in November-December last year, I already tried to work with this nuget, I had the same problem, requests were executed for 30-40 seconds. Then I abandoned the project on Xamarin and wrote on UWP, Telegram has a library in the form of an extension for Visual Studio.

**Comment by ForNeVeR** [comment] 2022-08-22 17:51
Please, someone find a clean set of steps to reproduce with the latest library version.

**Comment by antonGritsenko** [comment] 2022-08-22 18:03
@ForNeVeR OK, I did re-work of the code, now it looks like this (and all other methods also re-worked):

```
private void _telegramClient_ClientConnected(object sender, EventArgs e)
{
           TaskSyncHelper.ExecuteSync(async () => {
                Debug.WriteLine($"Loading chats...");
                Stopwatch stopwatch = new Stopwatch();
                stopwatch.Start();
                var testResult = await _telegramClient.GetChats();
                stopwatch.Stop();

                Debug.WriteLine($"GetChats execution time (sec): {stopwatch.Elapsed.TotalSeconds}");
            });
}
```

```
public static void ExecuteSync(Func<Task> action)
{
      action().NoAwait();
 }
```
NoAwait I took from your example.

Result:

With **SetLogVerbosityLevel(TdLogLevel.Error);**: GetChats execution time (sec): 9,6758372
Without **SetLogVerbosityLevel(TdLogLevel.Error);**: GetChats execution time (sec): 116,7462873

Same story for all other TDLib methods and events.

You can take the **no_db** branch from the repo, just run it and you will see the behavior.

**Comment by ForNeVeR** [comment] 2022-08-22 18:08
It is very strange that you're calling a method `ExecuteSync`, while it doesn't execute anything synchronously.

**Comment by antonGritsenko** [comment] 2022-08-22 18:17
@ForNeVeR bad naming, should be called ExecuteNoAwait

**Comment by ForNeVeR** [comment] 2022-08-22 18:19
@antonGritsenko, unfortunately, your program doesn't work for me. I've entered my phone number, received an authentication code and entered it, and then nothing. The authentication window was closed, the "main" window opened, and that's it. `_telegramClient_ClientConnected` was never called.

Please make a simpler reproducer, this is very hard to work with.

**Comment by antonGritsenko** [comment] 2022-08-22 18:26
@ForNeVeR you should wait about **3-4 minutes** until _telegramClient_ClientConnected executed (yes, huge delay as I wrote above). Just looking for $TdLib.TdApi+ConnectionState+ConnectionState* events in the Output.
Also you may restart the app, then it will be a bit faster, about 2-3 minutes.

**Comment by ForNeVeR** [comment] 2022-08-22 18:39
Okay, I got it running (had to path the hell out of it to make it work). Have you checked the log yourself? In my case, it generated 7 MiB of data during the `GetChats` call. Maybe that's just really actually slow?

**Comment by antonGritsenko** [comment] 2022-08-22 19:12
@ForNeVeR uncomment the line 49 of TClient.cs and compare ;)

**Comment by ForNeVeR** [comment] 2022-08-22 19:13
I have done that, and I still have the question.

**Comment by antonGritsenko** [comment] 2022-08-22 19:15
@ForNeVeR do you mean in your case the execution time with and without SetLogVerbosityLevel is the same?

**Comment by ForNeVeR** [comment] 2022-08-22 19:16
No, with logs is much slower. Thus my question:
> Have you checked the log yourself? In my case, it generated 7 MiB of data during the `GetChats` call. Maybe that's just really actually slow?

**Comment by antonGritsenko** [comment] 2022-08-22 19:18
@ForNeVeR then its weird. In my case **with** SetLogVerbosityLevel it MUCH faster: https://github.com/egramtel/tdsharp/issues/109#issuecomment-1222731646

**Comment by ForNeVeR** [comment] 2022-08-22 19:22
It is, yes. Because the default verbosity level is `Info` or something. So, by calling `_client.Bindings.SetLogVerbosityLevel(TdLogLevel.Error)`, you're effectively disabling the logs.

No logs = faster.

**Comment by ForNeVeR** [comment] 2022-08-22 19:24
Have you also tried running the app with and without debugger? In my case, it is almost instant (even if generating 7 MiB of logs) without debugger. And is noticeably slower with it attached (maybe because of the debug output).

**Comment by antonGritsenko** [comment] 2022-08-22 19:35
@ForNeVeR OK, next iteration of tests.
1. No, for me its the same with debugger attached or without.
2. OK, I changed line 49 to _client.Bindings.SetLogVerbosityLevel(TdLogLevel.Info) and got the same "slow" result (104 secs)
BUT as soon as I uncomment the line 46 (SetLogFilePath) is start working fast again (10 secs). Current code:
```
_client = new TdClient();
_client.Bindings.SetLogFilePath(Path.Combine(filesLocation, "tdlib.log"));
// this line make rocket from TDLib 
// https://github.com/egramtel/tdsharp/issues/109
_client.Bindings.SetLogVerbosityLevel(TdLogLevel.Info);
```

Now my question is: if SetLogFilePath is not set, where are logs stored?

**Comment by nikolaykusch** [comment] 2022-08-22 20:55
> @ForNeVeR OK, next iteration of tests.
> 
> 1. No, for me its the same with debugger attached or without.
> 2. OK, I changed line 49 to _client.Bindings.SetLogVerbosityLevel(TdLogLevel.Info) and got the same "slow" result (104 secs)
>    BUT as soon as I uncomment the line 46 (SetLogFilePath) is start working fast again (10 secs). Current code:
> 
> ```
> _client = new TdClient();
> _client.Bindings.SetLogFilePath(Path.Combine(filesLocation, "tdlib.log"));
> // this line make rocket from TDLib 
> // https://github.com/egramtel/tdsharp/issues/109
> _client.Bindings.SetLogVerbosityLevel(TdLogLevel.Info);
> ```
> 
> Now my question is: if SetLogFilePath is not set, where are logs stored?

And this already looks like the truth.
There is no access to the default path, an error occurs, it tries to write to the log and so on recursively. Hence the load on the processor and the long execution of requests.
At least for UWP and MAUI projects.

**Comment by antonGritsenko** [comment] 2022-08-22 23:08
> https://core.telegram.org/tdlib/docs/classtd_1_1_log.html

Very interesting. It marked as deprecated and there is no set_log_ile_path method available in the tdlib at all.

**Comment by ForNeVeR** [comment] 2022-08-24 17:47
https://github.com/tdlib/td/blob/8085779cdcf3b50372e05a613469c95d40207e9f/td/telegram/td_log.h#L23-L33

By default it claims writing to `stderr`. Which may not be available for a Windows subsystem app.

**Comment by antonGritsenko** [comment] 2022-09-02 01:10
OK, now I can confirm that nothing but TDLib itself is responsible for this behavior. I just re-wrote my app for using the native TDLib and got the same behavior. As soon as you not used the SetLogVerbosityLevel or SetLogStream you app will be extremely slow regarding events.

What about to change the WindowsBindings and add calling of the SetLogStream by default?

**Comment by ForNeVeR** [comment] 2022-10-12 18:42
Very suddenly, [the issue was fixed by the upstream](https://github.com/tdlib/td/commit/628b8901bc0c032a883d101724851e9f73c5b54b). There's nothing here for tdsharp to do.

**Closed by ForNeVeR** 2022-10-12 18:42 UTC
Labels: enhancement
